#!/bin/bash

chmod +x runner

sudo xcode-select --install
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
sudo chown -R $(whoami) /usr/local/var/homebrew
sudo chown -R $(whoami) /usr/local/Cellar

echo 'export PATH=/usr/local/bin:$PATH' >>~/.bash_profile
source ~/.bash_profile
brew install python3
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
